### ISSUE TITLE
No transparency in Mac OS Big Sur

### ISSUE THREAD

**Issue by hovnatan** [kirurobo/UniWindowController#21]
No transparency in Mac OS Big Sur. Can you please help?

**Comment by ahmedabdelkarim** [comment]
@hovnatan Same bug with me .. If you could solve it please share the solution and me too

**Comment by ahmedabdelkarim** [comment]
@hovnatan If you want to make app windows full screen add this script to the game object "UniWindowController"

using UnityEngine;
using System.Threading.Tasks;
using Kirurobo;

public class FullScreen : MonoBehaviour
{
    private UniWindowController uniwinc;

    async void Start()
    {
        // set application window resolution to screen resolution
        Screen.SetResolution(Screen.currentResolution.width, Screen.currentResolution.height, false);
        
        // must wait to apply window size change (which disables window transparency)
        await Task.Delay(500);

        // re-enable window transparency
        uniwinc = GameObject.FindObjectOfType<UniWindowController>();
        uniwinc.isTransparent = true;
        uniwinc.isTopmost = true;
        uniwinc.isHitTestEnabled = false;
    }

    void Update()
    {
        
    }
}

**Comment by kirurobo** [comment]
At least, the current version of LibUniWinC.bundle is not built for Apple silicon, so you need to select Intel 64-bit to run it for Unity 2020.3.

<img width="620" alt="build" src="https://user-images.githubusercontent.com/1019117/131942133-323ff514-e1c5-466e-bce9-eb8190cf6e68.png">

But that's not all. The window behavior is not stable in Unity 2020, e.g. it maximizes when transparency is enabled in my environment.
I haven't tried UniWinC in Unity 2020. I'll look into a solution...

**Comment by ahmedabdelkarim** [comment]
@kirurobo I could make it work on Unity 2019 as explained in my comments above. But still when I choose full screen or maximized widow from player settings, transparency and other properties do not work. I tried adding script to game object and set the properties again after some delay but didn't work.

Also how can I make the app appear on top of dock or top bar of macOS (but without full screen mode)?
