### ISSUE TITLE
Cannot show above top menu bar and Dock in macOS

### ISSUE THREAD

**Issue by ahmedabdelkarim** [kirurobo/UniWindowController#22]
I set isTopmost = True but the application window always appears behind top menu bar and Dock in macOS.
Making it full screen disables transparency.

How can I make it appear above everything and transparent?

**Comment by kirurobo** [comment]
I will fix the following in the next version.
- Change [NSWindow.Level](https://developer.apple.com/documentation/appkit/nswindow/level) from floating to popUpMenu
- The zoomed size will be the whole screen including the menu bar when the window is trasparent
- Maintaining transparency will be added in #21 

Thank you

**Comment by kirurobo** [comment]
I have released v0.8.1.
