### ISSUE TITLE
Live2Dとともに使用するとDragMoveCanvasが正常に動作しない

### ISSUE THREAD

**Issue by creeper-0910** [kirurobo/UniWindowController#57]
Live2Dを利用したプロジェクトで画像のようにシーン上に配置し、DragMoveCanvasのソート順を-99から100に変更して実行したのですが、正常にドラッグできませんでした。
その他、空のGameObjectにUniWindowDragMove.csを当ててみましたが変わりませんでした。
![image](https://github.com/kirurobo/UniWindowController/assets/56744841/0825110d-e60d-40a1-b8fd-75403e275502)

**Comment by kirurobo** [comment]
ご連絡ありがとうございます。

Live2D はあまり関係なく、EventSystem が無いからかもしれません。
ヒエラルキーの空欄右クリックから、UI → Event System を追加いただくといかがでしょうか？

DragMoveCanvas は uGUI を利用しているため、EventSystem が無いと反応できません。
すでに何らかの uGUI があれば EventSystem も通常存在するため DragMoveCanvas には EventSystem を含んでいませんが、もしヒエラルキーに無ければ追加する必要があります。

![EventSystem](https://github.com/kirurobo/UniWindowController/assets/1019117/037859d3-3ee9-49fc-959b-f61ea41ee728)

**Comment by creeper-0910** [comment]
正常に動作しました！
お手数をおかけして申し訳ありません、ありがとうございます！
