### ISSUE TITLE
Linux版について

### ISSUE THREAD

**Issue by creeper-0910** [kirurobo/UniWindowController#59]
難しいとは思いますが、もしLinuxに対応可能であれば対応して頂きたいです。
よろしくお願い致します。

**Comment by kirurobo** [comment]
* Windows、Mac とは大きく異なる実装が必要であること
* Windows、Mac のみでもなかなか保守できる体制は難しいこと
* 透過に関しては実装したとしても Windows、Mac と比較して劇的に重くなることが予想されること

などから、Linuxへの対応予定は現状ありません。
もし開発するとしても透過以外のウィンドウ移動やサイズ変更といった機能となるかと思います。
