### ISSUE TITLE
isMovableオプションを追加

### ISSUE THREAD

**Issue by creeper-0910** [kirurobo/UniWindowController#60]
複数のissueを立ててしまい申し訳ありません。
現在、DragMoveCanvasの有効・無効化をSetActiveで制御しているのですが、setActiveの処理が重いせいかUniWindowMoveHandle.csの82行目でスタックトレースエラーが発生し、終了してしまうようです。
isMovableオプションを追加することでsetActiveを使わずに処理できると思いますので、ご一考のほどよろしくお願い致します。

**Comment by kirurobo** [comment]
SetActive は負荷が高いため、enabled で有効・無効を切り替える作りにしてあります。

1. Start() の中でなど最初に UniWindowMoveHandle を取得しておく
  ```uniWinMoveHandle = GameObject.FindObjectOfType<UniWindowMoveHandle>();```

2. ```unniWinMoveHandle.enable = false``` など、必要なタイミングで enabled を切り替える

ということではいかがでしょうか。

参考 https://shibuya24.info/entry/unity-active

**Comment by creeper-0910** [comment]
返信ありがとうございます。
 以下のコードで試してみたのですが、エラーが発生してしまいました。
 ```
 public GameObject euniWinMoveHandle;
 private void Start()
 {
    euniWinMoveHandle = GameObject.FindObjectOfType<UniWindowMoveHandle>();
}
.
.
.
private void RemoveClick()
 {
    euniWinMoveHandle.enabled = false;
}
    ```
    
    ```
 `error CS0246: The type or namespace name 'UniWindowMoveHandle' could not be found (are you missing a using directive or an assembly reference?)`
 ```
 現在Unityの2022 3 8f1を使用しています。
 繰り返しの質問、申し訳ありません。解決策があればよろしくお願いいたします。

**Comment by kirurobo** [comment]
C# スクリプトの先頭に
```using Kirurobo;```
を追加していただく必要があるかと思います。

**Comment by creeper-0910** [comment]
すみません、書き忘れていました
using Kirurobo.UniWindowMoveHandle;
と記述していましたが、Kiruroboだけで大丈夫なのですね...試してみます!

**Comment by creeper-0910** [comment]
解決しました！
お手数おかけしてしまい申し訳ないです...
