### ISSUE TITLE
Picked color

### ISSUE THREAD

**Issue by XXXawdsasdawXXX** [kirurobo/UniWindowController#64]
Hello. I am using your Controller, thank you very much for such a tool. I want to create a desktop pet and often in such applications characters can sit on window elements, I tried to reproduce this effect. Unity API for reading pixel color (Texture2D.GetPixel) works only inside the game window. If your application is a transparent window, then the API will not be able to read colors outside of it.  I ask you to help in trying to find a solution and possibly update your Controller.

**Comment by kirurobo** [comment]
Do you want to capture any application window other than your own game window?
If so, how about [uWindowCapture](https://github.com/hecomi/uWindowCapture) or [uDesktopDuplication](https://github.com/hecomi/uDesktopDuplication)?

On the other hand, if you want to do any of the following, then another method seems better.
A. Read the color of a single pixel, like a color picker.
B. Want to know the window position and size of other applications

**Comment by XXXawdsasdawXXX** [comment]
Thank you, uWindowCapture helped.

**Comment by XXXawdsasdawXXX** [comment]
Thank you, uWindowCapture helped.
