### ISSUE TITLE
Apple SiliconのMacにてUnityのEditor上で動かそうとするとErrorとなる

### ISSUE THREAD

**Issue by nekomimimi** [kirurobo/UniWindowController#67]
以下のような事象に遭遇しましたのでご報告です。

### 事象
Apple SiliconのMacにてUnityのEdtor上で動かそうとするとErrorとなります。
エラーは以下のようにDllがみつからないとなります。
```
DllNotFoundException: LibUniWinC assembly:<unknown assembly> type:<unknown type> member:(null)
Kirurobo.UniWinCore.AttachMyWindow () (at Assets/Kirurobo/UniWindowController/Runtime/Scripts/LowLevel/UniWinCore.cs:453)
Kirurobo.UniWindowController.UpdateTargetWindow () (at Assets/Kirurobo/UniWindowController/Runtime/Scripts/UniWindowController.cs:769)
Kirurobo.UniWindowController.Update () (at Assets/Kirurobo/UniWindowController/Runtime/Scripts/UniWindowController.cs:484)
```
実行モジュールを作成した場合は、正常に動作しました。
UnityのEditor上で実行した場合のみのエラーとなります。

### 回避策
Intel CPU用のUnityを使えばエラーは出なくなります。

### 確認環境
PC: M1 Mac
Unity: 2023.2.20f1(Silicon) , 2022.3.11f1(Silicon)
(なお、2323.2.20f1(Intel)ではでは正常に動きました)

### その他
LibUniWinCのファイルを lipo -infoで確認したところ、確かにx86_64とarm64が含まれているため、何故、エラーとなるのかよくわかりませんでした。

**Comment by kirurobo** [comment]
ご報告ありがとうございます。

こちらは、.unitypackage ではなく UPM でインストールした場合でしょうか。
UPM からの場合、 Apple Silicon ではうまく動かない問題がありそうですが、その原因や対策はまだわかっていません。
同じファイルをプロジェクトに入れた場合には動きそうな気がしています。

一方、.unitypackage の場合でも、Unityのバージョンによっては .unitypackage エクスポート時に Mac 用の .bundle が壊れてしまうという問題があったようです。
https://forum.unity.com/threads/dylib-bundle-file-not-exporting-to-unity-package.427752/
v0.9.2 までの .unitypackage はその影響を受けているかもしれませんので、後日新しいバージョンのUnityを使ったバージョンにしてみます。

**Comment by nekomimimi** [comment]
返信ありがとうございます。
上のエラーはUPMから、
https://github.com/kirurobo/UniWindowController.git#upm 
でインストールしていました。

UniWinC_v0.9.2.unitypackageから入れてみたところ同じエラーが出ました。

そこで、bundleが壊れているではないかと思い、XCode 15.3でLibUniWinC.bundleをコンパイルし直して置き換えたところエラーが出なくなりました。

**Comment by kirurobo** [comment]
v0.9.3 として、.bundle を再作成し UPM にも反映させました。
こちらで Unity 2021.3.30f1 Apple Silicon および Intel で UPM からのインストールを試したところでは動作するようでした。

**Comment by kirurobo** [comment]
ご確認いただきありがとうございました。
こちらの Issue はクローズとさせていただきますね。
